### ISSUE TITLE
Error on GetIdsColliding when importing new rows

### ISSUE THREAD

**Issue by Loocos** [benwinding/react-admin-import-csv#84]
Hello there,

I'm wondering if that's the normal behaviour : 
- If I just export and re-import my CSV, I got my rows updated, that's well!
- If I export a CSV, edit it, add 1 row with a non existant ID, I'm going to get an error on GetIdsColliding because the request return a 404 not found.

I'm using API Platform for the data provider. Using your demo, it'll never happen because there's fake data (which not call any API)

How can I handle that behaviour to don't throw any error and create the concerned row ?
It is not automatic ? Should I use the callback from the ImportConfig in order to create it by myself ? 

I'm pretty sure that's not the goal or desired behaviour, I'm wrong ?

Any help would be really appreciated, thanks in advance!

![image](https://user-images.githubusercontent.com/26056280/159892020-a190734a-fc9b-433d-8d8b-9de1dc2eb486.png)

**Comment by benwinding** [comment]
Hi @Loocos,
Can't you just do the following:
1. Edit exported `posts.csv`
2. Import `posts.csv`
3. Click `Skip these rows` to ignore the rows that have conflicting id's

As shown here [in the demo](https://benwinding.github.io/react-admin-import-csv/#/posts):
![Kapture 2022-03-30 at 23 15 23](https://user-images.githubusercontent.com/11782590/160832487-dab3e5d7-cbbd-455a-b7b7-9e00033b9303.gif)

**Comment by Loocos** [comment]
@benwinding at least, can you just read what I wrote ? 
I know it and it's working like your "demo", but I'm not doing like your demo and the behaviour is totally different.


**If I export a CSV, edit it by adding 1 row with a non existant ID, I'm going to get an error on GetIdsColliding because the request return a 404 not found.**

If u follow what I just said, you'll not have any popup! But you looks to ignore that...

Fake data mean no API call, so you'll never have this problem on your demo.

**Comment by benwinding** [comment]
Sorry @Loocos, just trying to help you. Your original message wasn't very clear to me.

The demo uses the `ra-data-fakerest` dataprovider, which like you said _doesn't throw an error_ when you execute `getMany` for an `id` that doesn't exist, it should only return ones that do exist.

Which dataprovider are you using? You could fix this yourself by wrapping your dataprovider and catching the 404 errors before they reach this library.

**Comment by Loocos** [comment]
Hi @benwinding, sorry for the anwser delay, didn't got notified.

Tell me if I'm not clear enough, I will add the missing details. Anyway, I appreciate any help about it.

I'm using the fetch hydra from API Platform Admin.

I'm wondering how you guys are making it works without rewriting the getMany by yourself. Everybody must be confrontated to this problem.

So how your lib is working, allow users to only : 
- import a csv of non-existant entities
- import a csv of existant entities

but both at the same time won't work, are you agree with me ?
can the problem be solved by not forcing the usage of the getMany data provider (use the single get instead) ? But no option is currently available to handle this behaviour

I'm going to try something like you told me.

**Comment by benwinding** [comment]
Hi @Loocos,
I've added the option `disableGetMany`, this should fix the issue you're having. 
Try version `1.0.33` and let me know how you go 👍

**Comment by Loocos** [comment]
Hi @benwinding,

Thanks for the update. But I'm still having issues. 
I think it's not fit for API Platform. 

- it's now trying to always create instead of updating. (wasn't a problem before your update, so strange)
- the identifier isn't recognized anymore (I've an ID and EAN property, but the EAN is used as an identifier using @ApiProperty(identifier=true))

I think you should have a look to React-Admin & API Platform Admin.
Do you want me to make a public project to try this behaviour in order to improve your librairie?

**Comment by benwinding** [comment]
No worries @Loocos,

> Do you want me to make a public project to try this behaviour in order to improve your librairie?

Yeah create a project that demonstrates the issues, and I'll take a look 👌
