### ISSUE TITLE
CSV with empty column Error Handling

### ISSUE THREAD

**Issue by Talhafayyaz11** [benwinding/react-admin-import-csv#87]
When you try to import CSV with an empty column it throws an error in logging but there is no way to catch that error. I have tried to use papaparse skipEmpty lines option but that does not work either. Also tried validRow but I think the error is before executing that function. It would be great if you can help me out here. Thanks in advance.
<img width="1272" alt="Screenshot 2022-04-22 at 1 36 40 PM" src="https://user-images.githubusercontent.com/49181609/164651280-1f544ea4-d6e3-46a1-97d8-46dff11f2e56.png">

**Comment by benwinding** [comment]
Hey @Talhafayyaz11,
Thanks for reporting, definitely sounds like a bug, but I cannot reproduce it. A couple of questions will help us fix it.
1. Can you reproduce this bug on the demo site here -> https://benwinding.github.io/react-admin-import-csv/#/posts
2. What is in the file? Is it completely blank or still has headers?
2. What version of the library are you using? is it the latest version?

Let me know, and I'll try and get it fixed 👍

**Comment by Talhafayyaz11** [comment]
Hey @benwinding 
1. yes I just reproduced the same stack trace as I have attached above. 
2. This is the csv file [eventGoodCase.csv](https://github.com/benwinding/react-admin-import-csv/files/8539635/eventGoodCase.csv)
3. I am using the latest version: "react-admin-import-csv": "1.0.31"

**Comment by benwinding** [comment]
Thanks for those details @Talhafayyaz11, it was indeed a bug 🐛 . Basically [papaparse](https://www.papaparse.com/) returns empty columns as `null` which was unexpected.

It has been fixed via https://github.com/benwinding/react-admin-import-csv/commit/f8cdf38c17b96710a8f9f87a333fe53f793f3f65 . The new version `1.0.32` should have the fix in it. The demo should be fixed too 🙏

**Comment by Talhafayyaz11** [comment]
@benwinding  can you let me know how can I catch the error? Because it still throws me error.
